import Head from 'next/head'

function Layout({children}) {
  return (
    <div className='container'>
      <Head>
        <title>Next-Quiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/quizIcon.png"/>
      </Head>
        {children}
    </div>
  )
}

export default Layout